name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:  # 👈 Mauvaise indentation corrigée ici
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: .  # Remplace par le dossier contenant ton site (ex: ./dist)
          publish_branch: gh-pages
